@startuml

entity "TB_media_types" as e01{
  * id: INTEGER
  --
    Name: NVARCHAR(120)
}
entity "TB_genres" as e02{
  * GenreId: INTEGER
  --
    Name: NVARCHAR(120)
}
entity "TB_tracks" as e03{
  * playlist_track_id: INTEGER
  --
    Name: NVARCHAR(200)
    albums_id: INTEGER
    media_types_id: INTEGER
    genres_id: INTEGER
    Composer: NVARCHAR(220)
    Miliseconds: INTEGER
    Bytes: INTEGER
    UnitPrice: NUMERIC 
}
entity "TB_playlists" as e04{
    *id: INTEGER
    --
    Name: NVARCHAR(120)
}
entity "TB_playlist_track" as e05{
    *playlist_id: INTEGER
    *id: INTEGER
}
entity "TB_artists" as e06{
    *id: INTEGER
    --
    Name: NVARCHAR(120)
}
entity "TB_albums" as e07{
    *id: INTEGER
    --
    Title: NVARCHGAR(160)
    artists_id: INTEGER
}
entity "TB_employees" as e08{
    *id: INTEGER
    --
    LastName: NVARCHAR(20)
    FirstName: NVARCHAR(20)
    Title: NVARCHAR(30)
    Reportsto: INTEGER
    BirthDate: DATATIME
    HireDate: DATETIME
    Adress: NVARCHAR(70)
}
entity "TB_costumers" as e09{
  *id: INTEGER
  --
  FirstName: NVARCHAR(40)
  LastName: NVARCHAR(20)
  Company: NVARCHAR(80)
  Adress: NVARCHAR(70)
  City: NVARCHAR(40)
  Stat: NVARCHAR(40)
  Country: NVARCHAR(40)
  PostalCode: NVARCHAR(10)
  Phone: NVARCHAR(24)
  Fax: NVARCHAR(24)
  Email: NVARCHAR(60)
  SupportRepId: INTEGER
}
entity "TB_invoices" as e10 {
  *id: INTEGER
  --
  costumers_id: INTEGER
  InvoiceDate: DATETIME
  BillingAddress: NVARCHAR(50)
  BillingCity: NVARCHAR(50)
}
entity "TB_invoice_items" as e11{
  *id: INTEGER
  --
  invoices_id: INTEGER
  tracks_id: INTEGER
  UnitPrice: NUMERIC
  Quantity: INTEGER
}
e01 ||--o{ e03
e03 }o--o| e02
e05 |o--|| e04
e05 |o--|| e03
e06 ||--o{ e07
e07 |o--o{ e03
e08 |o--o{ e09
e09 ||--o{ e10
e10 ||--o{ e11
e11 }o--|| e03

@enduml